CREATE VIEW VIEW_USER_INFORMATION AS
    SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH, U.GENDER,
           C1.CITY_NAME, C1.STATE_NAME, C1.COUNTRY_NAME,
           C2.CITY_NAME AS HOMETOWN_NAME, C2.STATE_NAME AS HOMETOWN_STATE, C2.COUNTRY_NAME AS HOMETOWN_COUNTRY,
           P.INSTITUTION, E.PROGRAM_YEAR, P.CONCENTRATION, P.DEGREE
    FROM (((((USERS U LEFT JOIN USER_CURRENT_CITIES UCC ON U.USER_ID = UCC.USER_ID) LEFT JOIN CITIES C1 ON UCC.CURRENT_CITY_ID = C1.CITY_ID)
          LEFT JOIN USER_HOMETOWN_CITIES UHC ON U.USER_ID = UHC.USER_ID) LEFT JOIN CITIES C2 ON UHC.HOMETOWN_CITY_ID = C2.CITY_ID)
          LEFT JOIN EDUCATION E ON U.USER_ID = E.USER_ID) LEFT JOIN PROGRAMS P ON E.PROGRAM_ID = P.PROGRAM_ID;

CREATE VIEW VIEW_ARE_FRIENDS AS
    SELECT F.USER1_ID, F.USER2_ID
    FROM USERS U JOIN FRIENDS F ON U.USER_ID = F.USER1_ID;

CREATE VIEW VIEW_PHOTO_INFORMATION AS
    SELECT A.ALBUM_ID, U.USER_ID, CP.PHOTO_ID AS COVER_ID, A.ALBUM_NAME, A.ALBUM_CREATED_TIME, A.ALBUM_MODIFIED_TIME, A.ALBUM_LINK, A.ALBUM_VISIBILITY,
           P.PHOTO_ID, P.PHOTO_CAPTION, P.PHOTO_CREATED_TIME, P.PHOTO_MODIFIED_TIME, P.PHOTO_LINK
    FROM ((ALBUMS A JOIN USERS U ON A.ALBUM_OWNER_ID = U.USER_ID) JOIN PHOTOS CP ON A.COVER_PHOTO_ID = CP.PHOTO_ID)
          JOIN PHOTOS P ON A.ALBUM_ID = P.ALBUM_ID;

CREATE VIEW VIEW_EVENT_INFORMATION AS
    SELECT UE.EVENT_ID, UE.EVENT_CREATOR_ID, UE.EVENT_NAME, UE.EVENT_TAGLINE, UE.EVENT_DESCRIPTION, UE.EVENT_HOST, UE.EVENT_TYPE,
           UE.EVENT_SUBTYPE, UE.EVENT_ADDRESS, C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME, UE.EVENT_START_TIME, UE.EVENT_END_TIME
    FROM USER_EVENTS UE JOIN CITIES C ON UE.EVENT_CITY_ID = C.CITY_ID;

CREATE VIEW VIEW_TAG_INFORMATION AS
    SELECT T.TAG_PHOTO_ID, T.TAG_SUBJECT_ID, T.TAG_CREATED_TIME, T.TAG_X, T.TAG_Y
    FROM TAGS T;