DROP TABLE TAGS;

DROP TRIGGER photo_trigger;
DROP SEQUENCE photo;
DROP TABLE PHOTOS;

DROP TRIGGER album_trigger;
DROP SEQUENCE album;
DROP TABLE ALBUMS;

DROP TABLE PARTICIPANTS

DROP TRIGGER event_trigger;
DROP SEQUENCE event;
DROP TABLE USER_EVENT;

DROP TABLE EDUCATION;

DROP TRIGGER program_id_generate;
DROP SEQUENCE program;
DROP TABLE PROGRAMS;

DROP TRIGGER message_id_generate;
DROP SEQUENCE message;
DROP TABLE MESSAGES;

DROP TABLE USER_HOMETOWN_CITIES;
DROP TABLE USER_CURRENT_CITIES;

DROP TRIGGER city_id_generate;
DROP SEQUENCE city;
DROP TABLE CITIES;

DROP TRIGGER order_friends_pairs;
DROP TABLE FRIENDS;

DROP TRIGGER user_id_generate;
DROP SEQUENCE user_sequence;
DROP TABLE USERS;
